// <auto-generated />
using AnimalsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalsApi.Migrations
{
    [DbContext(typeof(AnimalsApiContext))]
    [Migration("20231115042311_UpdateController")]
    partial class UpdateController
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalsApi.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Description = "Long black hair, no tail",
                            Name = "Matilda",
                            Species = "Canine"
                        },
                        new
                        {
                            AnimalId = 2,
                            Description = "Orange, white spots.",
                            Name = "Chumley",
                            Species = "Feline"
                        },
                        new
                        {
                            AnimalId = 3,
                            Description = "Simese",
                            Name = "Missy",
                            Species = "Feline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
